name: noria_checkout_example
description: Noria Checkout integration example.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  noria_checkout:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
